#!/bin/sh
#
# Start guppyscreen
#

GUPPYSCREEN=/root/guppyscreen/guppyscreen
PID_FILE=/run/guppyscreen.pid
NICENESS=10

start() {
    backlight 0
    /etc/init.d/S35tslib start
    backlight 75
    killall guppyscreen
    start-stop-daemon -S -b -m -p $PID_FILE -N $NICENESS --exec /bin/sh -- -c $GUPPYSCREEN
}

stop() {
    /etc/init.d/S35tslib stop
    killall guppyscreen
}

restart() {
    stop
    sleep 2
    start
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart|reload)
        restart
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
